add chiselDB, just compare with the main branch
OpenXiangShan/tl-test pull request #6
Opened 2022-11-27 12:49 UTC by gravelcai

not complete yet:
	* succeed in dumping .db file.
	* .db file is empty.

2022-11-27 12:52 UTC, gravelcai commented
now is able to generate .db file when add --dump-db option. but the .db file is empty and I have no idea now.

2022-11-28 11:00 UTC, wakafa1 requested changes

2022-11-28 11:00 UTC, wakafa1 commented on Emu/Emu.cpp
> +        { "dump-db",    0, NULL,  6  },
要不取一个有意义的字母？比如 d

2022-11-29 05:47 UTC, gravelcai commented on Emu/Emu.cpp
> +        { "dump-db",    0, NULL,  6  },
已删除 Makefile。

2022-11-30 01:51 UTC, gravelcai commented on Makefile
> +init:
已去掉 Makefile

2022-11-30 01:55 UTC, gravelcai commented on Emu/Emu.cpp
> +        { "dump-db",    0, NULL,  6  },
改成了 d，但没有给 --dump-db 加进短命令。现在是根据 cmake 时的加的命令行选项对 Emu 里的 --dump-db 的代码条件编译，这里就少写一个条件编译，免得代码看起来太花里胡哨(￣y▽,￣)╭

2022-11-30 01:57 UTC, wakafa1 approved these changes

2022-11-30 02:02 UTC, merged